### ISSUE TITLE
教学地点不同导致课程时间不同如何解决

### ISSUE THREAD

**Issue by ZWL42** [junyilou/python-ical-timetable#4]
例如全校的第三节课的开始时间是10点20分，而全校5楼以上楼层的开始时间是10点15分。
请问有什么解决办法呢？

**Comment by DrhyLee** [comment]
你好，这是我本科时期的项目，如今我也在做硕士这所学校的适配，更改时间很容易，你需要设定每节课的开始结束时间，请仔细阅读代码，你可以找到生成一个类似202209261900这样内容的部分

**Comment by DrhyLee** [comment]
这个问题解决得大规模改动代码，可以但不建议你这么做，因为本身没必要追逐五分钟的时间吧😂我自己都用整点的时间，如果你想做改动思路如下：检查教室信息，比对关键字比如601中，6>5因而将时间改为15，可以解决问题

**Comment by ZWL42** [comment]
嗯嗯，我也有想过类似关键字匹配，但我刚刚开始用py，没系统地学过。所以可能加代码都比较麻烦（

**Comment by DrhyLee** [comment]
OK，你有心能着手开始做就是一件很不错的事
我python也不是很好，这个东西多动手多花点时间会有收效

**Comment by ZWL42** [comment]
嗯嗯，那具体应该怎么写呢？请指教。

**Comment by DrhyLee** [comment]
这个问题我只能给你提供思路，参见我上述的comment
你的思路总体上还是要拆解字符串，找到教室所在的楼层，每个学校都不一样，这我没办法帮助你，拆解出来楼层后，再去与5比较，设定条件分支结构来根据不同楼层做不同的时间匹配。大致就是这样

**Comment by ZWL42** [comment]
嗯，好的，我再学习一下后自己解决吧，谢谢了。

**Comment by junyilou** [comment]
现在的代码没有针对这种情况做适配，我提供两个简单的解决思路
其实跟楼上说的差不多，只是我就写成代码了
P.S. 为什么这位朋友有种自己是原作者的感觉？

### 第一种是比较模块化的办法，适合更宽的情况

**在 school.py 中**
原本有这行代码，表示所有上课的时间
```python
classTime = [(8, 0), (14, 10), (20, 20)]
```

您可以添加一行新的数组，作为全校五层以上的上课时间，例如：
```python
classTimeAlternative = [(7, 55), (14, 5), (20, 15)]
```
需要注意的是，使用这种方法，您应该确保新的 classTime 数组依然列举出一天全部课程的时间，而不是只提供部分课程

然后，**在 timetable.py 中**，注意到有
```python
startTime = classTime[classOrder[0]]; endTime = classTime[classOrder[-1]]
```

这行代码的意思是从 classTime 数组中取出第一个课时上课的时间和最后一个课时上课的时间。所以，您可以通过 if 语句进行判断，修改原来的代码如下：

```python
if int(Location[1]) >=5: 
#这里假设您的教室名字类似于 ABCC，其中 B 表示楼层，所以取 ABCC 的第 2 位转换为数字进行对比
    startTime = classTimeAlternative[classOrder[0]]; endTime = classTimeAlternative[classOrder[-1]]
    # 在这样的情况下，不再使用 classTime，而是使用我们刚刚创建的新的 classTimeAlternative
else:
    startTime = classTime[classOrder[0]]; endTime = classTime[classOrder[-1]]
    # 否则，使用默认的 classTime 数组
```

### 或者您只是想简单的加 15 分钟的话

那就只修改 timetable.py 就可以了，比如说：

```python
offset = 15 if int(Location[1]) >=5 else 0 # 如果是五楼以上，设置偏差 15 分钟，否则偏差 0
classStartTime = classDate + timedelta(minutes = startTime[0] * 60 + startTime[1] + offset)
classEndTime = classDate + timedelta(minutes = endTime[0] * 60 + endTime[1] + school.classPeriod + offset)
# 在计算课程的开始和结束时间，加上我们刚刚设置的偏差分钟数
```
