### ISSUE TITLE
请求添加FJNU-ics至README.md

### ISSUE THREAD

**Issue by payphone-x** [junyilou/python-ical-timetable#5]
你好，我是福建师范大学（FJNU）的一名学生。最近我和同学在你的项目基础上制作了FJNU的课表自动生成程序 [FJNU-ics](https://github.com/payphone-x/FJNU-ics)，故请求将我们的项目加至 README.md 中。谢谢。

**Comment by DrhyLee** [comment]
很开心你能基于我的项目进行开发，因平时代码时间少，没怎么上传过我的项目。请移步到我的项目readme.md下看看我刚更新的是否合适，谢谢

**Comment by DrhyLee** [comment]
另外看你们都叫xxx-ics，我也将我的项目名改为了UPC-ics

**Comment by junyilou** [comment]
多谢，会在稍后更新添加。
