### ISSUE TITLE
关于日历提醒的问题

### ISSUE THREAD

**Issue by hiBenzhu** [junyilou/python-ical-timetable#6]
想请教一下就是每节课开始前十分钟或者十五分钟之前提醒 这个该怎么实现

**Comment by hiBenzhu** [comment]
已解决

**Comment by hiBenzhu** [comment]
没解决

**Comment by junyilou** [comment]
粗略的研究了一下：

一个日历项称为 VEVENT，在其当中可以设置一个提醒项 VALARM。让我们来看这样一个例子：

```
BEGIN:VCALENDAR
BEGIN:VEVENT
DTEND;TZID=Asia/Shanghai:20230213T220000
DESCRIPTION:测试描述
UID:ad021f-120310-ffeabc-098182
DTSTAMP:20230213T123456Z
URL;VALUE=URI:
SUMMARY:测试标题
DTSTART;TZID=Asia/Shanghai:20230213T205100
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER:-PT15M
UID:da021f-120310-ffeabc-728384
END:VALARM
END:VEVENT
END:VCALENDAR
```

注意到中间的这一段代表日历提醒

```
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER:-PT15M
UID:da021f-120310-ffeabc-728384
END:VALARM
```

其中：
* `ACTION:DISPLAY` 在 iOS 上称为「带声音的信息」，也是最普通的一种提醒，macOS 日历显示还可以设置为「电子邮件」或者「打开文件」，但是似乎并不是很实用
* `TRIGGER:-PT15M` 代表的是在日历发生的 15 分钟以前提醒，如果想设置为 15 分钟以后则是 `TRIGGER:PT15M`，类似的还有 `PT15H` 代表 15 小时以后、`PT0S` 代表发生的时刻（相差 0 秒）
* 如果想在一个精确时间提醒的话，写为 `TRIGGER;VALUE=DATE-TIME:20230213T155900Z`，表示北京时间 2 月 13 日 23 时 59 分发出提醒，由于这个文字没有加时区所以是按照 UTC 时间来的
* 每个 VALARM 对象也有自己的 UID 唯一识别码

因此以课前十分钟发出提醒为例，修改第 45 行 `iCal += ` 之后的内容如下：

```python
iCal += f"""
BEGIN:VEVENT
DTEND;TZID=Asia/Shanghai:{EndTime}
DESCRIPTION:{Description}
UID:{uid_generate(Name + StartTime)}
DTSTAMP:{runtime}
URL;VALUE=URI:
SUMMARY:{Title}
DTSTART;TZID=Asia/Shanghai:{StartTime}
{school.geo(Location)}
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER:-PT10M
UID:{uid_generate(Name + StartTime + "ALARM")}
END:VALARM
END:VEVENT"""
```

就可以了，其中 `{uid_generate(Name + StartTime + "ALARM")}` 只要保证 `uid_generate` 括号里的内容在整个文件中唯一即可，这里就随便加了一个 "ALARM" 文字
