### ISSUE TITLE
配置好Apple Maps位置信息后，生成ICS文件没有相关信息

### ISSUE THREAD

**Issue by LinxHex** [junyilou/python-ical-timetable#7]
![image](https://github.com/junyilou/python-ical-timetable/assets/92703641/97dc002b-771d-4e83-b600-33824566b7f2)
![image](https://github.com/junyilou/python-ical-timetable/assets/92703641/ccf6abe6-cbd4-4982-ba32-5e0793d635b3)

**Comment by junyilou** [comment]
> 之前代码在这方面的比较陈旧和蠢，最近重写了这一部分，现在不需要手动去编写繁杂的 Apple Maps 信息了，可以直接从创建好的日历中提取，欢迎再次尝试！
