### ISSUE TITLE
UESTC可以用飞书生成caldav账号密码进行日历同步

### ISSUE THREAD

**Issue by DarriusL** [junyilou/python-ical-timetable#9]
https://www.feishu.cn/hc/zh-CN/articles/360043178673-%E8%AE%BE%E7%BD%AE%E6%9C%AC%E5%9C%B0%E7%B3%BB%E7%BB%9F%E6%97%A5%E5%8E%86%E4%B8%8E%E9%A3%9E%E4%B9%A6%E6%97%A5%E5%8E%86%E4%B9%8B%E9%97%B4%E7%9A%84%E5%8D%95%E5%90%91%E5%90%8C%E6%AD%A5

至于outlook用户可以使用Outlook CalDav Synchronizer（https://caldavsynchronizer.org/， https://www.webdavsystem.com/server/access/caldav/ms_outlook_caldav_synchronizer/ ）在PC端导入至outlook

**Comment by junyilou** [comment]
感谢分享，但并不与本项目内容冲突

**Comment by DarriusL** [comment]
只是分享给懒得折腾的朋友😁


祝好！





________________________________
发件人: Junyi Lou ***@***.***>
发送时间: 2024年4月15日 14:18
收件人: junyilou/python-ical-timetable ***@***.***>
抄送: Junwei Lei ***@***.***>; Author ***@***.***>
主题: Re: [junyilou/python-ical-timetable] UESTC可以用飞书生成caldav账号密码进行日历同步 (Issue #9)


感谢分享，但并不与本项目内容冲突
